### ISSUE TITLE
Alternative for testing Enhance components

### ISSUE THREAD

**Issue by christian-bromann** [enhance-dev/enhance.dev#111]
I've seen that you added documentation for Enhance component testing with Playwright. Would you be open to also have an alternative solution that is more based on web standards, e.g. WebdriverIO? It just released component testing primitives and has Enhance as one of their [examples](https://github.com/webdriverio/component-testing-examples/blob/main/enhance/tests/specs/example.test.js).

✌️ Cheers
A WebdriverIO Maintainer 😉

**Comment by kristoferjoseph** [comment]
Definitely!
We are not very happy with Playwright and have been experimenting with different approaches.
Please feel free to add a new doc to the testing section.
Very interested in hearing more.

**Comment by kristoferjoseph** [comment]
@christian-bromann Any interest in making a PR for this?
I am actively adding examples of front-end component testing in HTML pages.
Could some WebdriverIO examples be useful here?

**Comment by christian-bromann** [comment]
@kristoferjoseph please see #132

> We are not very happy with Playwright

I believe PW is the wrong choice for developers, even though their DX is great, as their proprietary automation goes beyond the abilities of what a user can/would do. I've started some [research on this](https://github.com/webdriverio/component-testing-examples/blob/main/framework-comparisons/README.md).

**Comment by waldyrious** [comment]
I was going to suggest that this issue be closed following the merge of #132, but I just noticed that the docs changed in that PR (https://enhance.dev/docs/learn/practices/testing/ and https://enhance.dev/docs/learn/practices/testing/webdriverio) are not connected to the docs that mention Playwright (https://enhance.dev/docs/by-example/examples/browser-testing).

In fact, the entire [By example](https://enhance.dev/docs/by-example/) section of the docs seems disconnected from the rest of the site, with a separate sidebar and everything. Is this intentional? I would expect at least the Playwright and WebDriverIO docs to link to each other.

**Comment by christian-bromann** [comment]
> I was going to suggest that this issue be closed following the merge of #132

Good point, I will go ahead and close.

> the entire [By example](https://enhance.dev/docs/by-example/) section of the docs seems disconnected from the rest of the site

Yep, I guess this should be tracked as a different issue.
