### ISSUE TITLE
Disjointed sets of docs?

### ISSUE THREAD

**Issue by waldyrious** [enhance-dev/enhance.dev#139]
_Note: the issue below was first noticed in https://github.com/enhance-dev/enhance.dev/issues/111#issuecomment-1442737425; I'm opening a new issue to track it separately._

The docs for browser testing using WebDriverIO  (https://enhance.dev/docs/learn/practices/testing/webdriverio) are linked to from https://enhance.dev/docs/learn/practices/testing/, but they are not connected to the docs that mention Playwright (https://enhance.dev/docs/by-example/examples/browser-testing).

In fact, the entire [By example](https://enhance.dev/docs/by-example/) section of the docs seems disconnected from the rest of the site, with a separate sidebar and everything. Is this intentional?

**Comment by kristoferjoseph** [comment]
Yes this is on purpose.

**Comment by kristoferjoseph** [comment]
We have been gathering the example content based on user feedback but we are trying to come up with a way to promote our recommended approaches while still creating content we need to verify and sit with for a bit to determine if they are frictionless enough to be promoted to our main content sections.

**Comment by waldyrious** [comment]
I see. So am I right to assume that eventually the Playwright documentation at https://enhance.dev/docs/by-example/examples/browser-testing might be moved to be under https://enhance.dev/docs/learn/practices/testing/, alongside the WebDriverIO docs which are [already there](https://enhance.dev/docs/learn/practices/testing/webdriverio)?

**Comment by kristoferjoseph** [comment]
We are going to continue to get user feedback on these testing approaches.

The plan has always been to have three top-level tabs in the Enhance.dev docs; Learn, Examples, and Reference.

During the beta we want users to be focusing on the Learn content which is what is currently available on the site.
Since the WebDriverIO content was from an external PR I felt it could go in the main sidebar to gauge users interest.

Based on initial feedback the WebDriverIO content does not fit with the overall ethos of Enhance and will most likely be moved to the Example section after the 1.0 release since the examples section will focused on how to use library 'X' with Enhance.

**Comment by waldyrious** [comment]
Makes sense — thanks for the explanation and context!
